### ISSUE TITLE
Doors at Luigis place don't open

### ISSUE THREAD

**Issue by christooss** [rwengine/openrw#51] opened 2016-05-23 14:06 UTC
I'm scene where Luigi gives you Luigis girls mission characters clip through the door when they come to talk with you.

**Comment by parkerlreed** [comment] 2016-05-24 03:51
The regular game is working for you? It get to the very first scene with the burning car and just stops for me.

**Comment by TacoDeBoss** [comment] 2016-05-24 03:52
@parkerlreed That's because you're running libsfml-dev 2.3. On systems with libsfml-dev 2.1, the game gets past that point. Currently it doesn't due to a regression in SFML 2.3.

**Comment by parkerlreed** [comment] 2016-05-24 03:56
Ahh thanks. Yeah Arch repo has 2.3 

````
1 community/sfml 2.3.2-4 [installed]
      A simple, fast, cross-platform, and object-oriented multimedia API
````

**Comment by christooss** [comment] 2016-05-24 09:43
@parkerlreed you can "solve" this if you exchange all wav files in gtainstallfolder/audio with these: https://github.com/christooss/gta3audiofiles/blob/master/audio.zip

These are empty wav files but they play (heh) correctly so game continues to play on. Just without sounds outside the recorded scene.

**Comment by JayFoxRox** [comment] 2016-08-27 11:32
I feel like this is an easy fix, presumably just setting script objects invisible - either all of them during cutscenes, or just selectively using the script.

This happens in most (all?) luigi missions. Script thread names would be luigi2, luigi3, luigi4.

This could be related to:

```
0363: toggle_model_render_at 890.875 -416.875 15.0 radius 6.0 object #BACKDOOR 0 
```

which is ran before the cutscene. The name "set visibility of closest object of type" hints that this only controls 1 object.
There is an equivalent call to 0363 with 1 as last parameter after the cutscene.

**Comment by JayFoxRox** [comment] 2016-08-30 16:41
Consider it fixed. I'll open a PR once the new script system is merged.

**Closed** 2016-08-31 21:08 UTC
