### ISSUE TITLE
Character control quirks

### ISSUE THREAD

**Issue by vflyson** [rwengine/openrw#208] opened 2016-08-16 02:16 UTC
Been testing the controls today, found a few small quirks:
1. The character will double-jump frequently when pressing <kbd>Space</kbd>.
2. Holding <kbd>W</kbd> or <kbd>Shift</kbd>+<kbd>W</kbd> and then pressing <kbd>Esc</kbd> will make the character run until you press the same control button again upon exiting the game menu. 
3. Related to the previous issue. The direction of the movement will change upon pressing the <kbd>Esc</kbd> the second time upon returning to the game.

Note: the first two issues will happen with any movement key.

_(Markup fixed by JayFoxRox)_

**Comment by danhedron** [comment] 2016-09-11 22:46
The issue is a lack of double-buffering in GameInputState. The pressed check should check against the previous frame instead of returning true for the duration of the press.

**Comment by danhedron** [comment] 2016-11-20 00:16
Fixed with #248

**Closed by danhedron** 2016-11-20 00:16 UTC
Labels: bug
