### ISSUE TITLE
Jumping triggers at least twice

### ISSUE THREAD

**Issue by PerikiyoXD** [rwengine/openrw#240] opened 2016-09-11 22:23 UTC
If you press Space (aka Jump key), it will trigger jump several times. It happens because each tick/frame will detect if key is down, while it should check if the key was pressed once, and when it was unpressed.

There is a way to remove this, by registering each key to a class which checks the key is up or down with a bool.

**Comment by danhedron** [comment] 2016-09-11 22:52
Duplicate of #208.

**Closed by danhedron** 2016-09-11 22:52 UTC
