### ISSUE TITLE
Build failed on macOS

### ISSUE THREAD

**Issue by snshn** [rwengine/openrw#684] opened 2019-01-10 06:59 UTC
macOS 10.14

Full log:
```
FruityComputy:build user$ ./build.sh 
-- Building OpenRW GIT SHA1: 21da262a64ea5d30d516f5ddc0f957ea47ce50f7
-- Boost version: 1.68.0
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   program_options
--   system
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Found FFmpeg: /usr/local/lib/libavcodec.dylib (found version "4.1") 
-- Found SDL2: /usr/local/lib/libSDL2.dylib (found version "2.0.9") 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/user/Projects/OpenRW/openrw.git/build
[  1%] Building C object rwcore/CMakeFiles/rwcore.dir/gl/gl_core_3_3.c.o
[  2%] Building CXX object rwcore/CMakeFiles/rwcore.dir/gl/DrawBuffer.cpp.o
[  3%] Building CXX object rwcore/CMakeFiles/rwcore.dir/gl/GeometryBuffer.cpp.o
[  4%] Building CXX object rwcore/CMakeFiles/rwcore.dir/gl/TextureData.cpp.o
[  5%] Building CXX object rwcore/CMakeFiles/rwcore.dir/rw/abort.cpp.o
[  6%] Building CXX object rwcore/CMakeFiles/rwcore.dir/platform/FileIndex.cpp.o
[  7%] Building CXX object rwcore/CMakeFiles/rwcore.dir/data/Clump.cpp.o
[  8%] Building CXX object rwcore/CMakeFiles/rwcore.dir/fonts/FontMap.cpp.o
[  9%] Building CXX object rwcore/CMakeFiles/rwcore.dir/fonts/FontMapGta3.cpp.o
[ 10%] Building CXX object rwcore/CMakeFiles/rwcore.dir/fonts/GameTexts.cpp.o
[ 11%] Building CXX object rwcore/CMakeFiles/rwcore.dir/fonts/Unicode.cpp.o
[ 12%] Building CXX object rwcore/CMakeFiles/rwcore.dir/loaders/LoaderIMG.cpp.o
[ 13%] Building CXX object rwcore/CMakeFiles/rwcore.dir/loaders/LoaderDFF.cpp.o
[ 14%] Building CXX object rwcore/CMakeFiles/rwcore.dir/loaders/LoaderSDT.cpp.o
[ 15%] Building CXX object rwcore/CMakeFiles/rwcore.dir/loaders/LoaderTXD.cpp.o
[ 17%] Linking CXX static library librwcore.a
ar: -no_warning_for_no_symbols: No such file or directory
make[2]: *** [rwcore/librwcore.a] Error 1
make[2]: *** Deleting file `rwcore/librwcore.a'
make[1]: *** [rwcore/CMakeFiles/rwcore.dir/all] Error 2
make: *** [all] Error 2
```

Here's the libtool version:
```
FruityComputy:build user$ libtool -V
Apple Inc. version cctools-921.0.1
```

I could try switching to glibtool, not sure if it'd help though.

Any help would be appreciated.

**Comment by christoph-heiss** [comment] 2019-01-10 07:55
You can try to invoke cmake with `-G Xcode` and then compile using `xcodebuild -configuration Release` or `xcodebuild -configuration Debug`, respectively.

I currently have a fix for that pending in #675, so for the meantime Xcode can be used to build OpenRW on macOS. (macOS is a really annoying target due to having a constantly broken build process).

**Comment by vflyson** [comment] 2019-01-10 13:57
Yeah, I feel like Apple is quite selfish when it comes to making changes. Thank you for the tips @christoph-heiss!

**Comment by madebr** [comment] 2019-01-10 15:06
Thanks @christoph-heiss !
Does this mean the information on the wiki is wrong?

I have another little question:
Does openrw build on macosx when using the gcc or clang toolchain?

**Comment by christoph-heiss** [comment] 2019-01-10 16:37
I would not consider to be wrong per se, it is just that macOS 10.14 broke building with Make/Ninja again.

The “official” on travis CI is too build using Xcode - so maybe remark that in the wiki.

OpenRW does build with both, (homebrew’d) clang and gcc-8, it is just a matter of wrong compiler flags being passed.

**Comment by vflyson** [comment] 2019-01-14 03:21
I was able to build openrw using Xcode following your tips, thank you @christoph-heiss 
Not closing the issue as this build method is not consistent with what's in the wiki, but please feel free to close it any time, before or after being fixed.

**Comment by Patrik356b** [comment] 2019-01-14 17:13
Better to keep it open until fixed imho

**Comment by madebr** [comment] 2019-01-15 08:21
I've edited the build instructions in the wiki to include the following command to build openrw for visual studio and xcode:
```
cmake --build . --config Release
```

**Comment by damianbal** [comment] 2019-05-11 07:14
> I've edited the build instructions on the wiki to include the following command to build openrw for visual studio and xcode:
> 
> ```
> cmake --build . --config Release
> ```

That doesn't work for me on Mojave, I tried Debug as well no luck.

**Comment by madebr** [comment] 2019-05-11 12:36
@damianbal 
I've updated the Mac OS X version to 10.14.4 on travis CI: https://travis-ci.org/madebr/openrw/jobs/531108431
It does not reproduce your problem.

Can you please post the complete output of configuration + build to a gist? Thanks!

**Comment by gbudny** [comment] 2019-07-28 12:32
I have a different issue when I try to compile it  :

https://gist.github.com/gbudny/f3aa6ddab63bff5e3bcdeb8406daec04

**Comment by dracc** [comment] 2019-07-28 12:44
@gbudny; What's your output from running `ar -V`?

**Comment by gbudny** [comment] 2019-07-28 13:13
@dracc @damianbal

Thanks. 

I compiled it, but I see many warnings:

https://gist.github.com/gbudny/ce949696839ecdbdb2ce4b080cbc9d3a

**Comment by tsjost** [comment] 2021-10-14 22:13
Building on Mac now works with both Xcode and regular Makefile!

**Closed by tsjost** 2021-10-14 22:13 UTC
Labels: mac, build
