### ISSUE TITLE
Crash, dereferencing null ptr

### ISSUE THREAD

**Issue by ShFil119** [rwengine/openrw#336] opened 2017-10-27 21:05 UTC
Dereferencing ScriptObjectType with null instance CharacterObject
It refers to debugging overload from file ScriptTypes.hpp, which catch reason of crash.
Problem:
Game crashes by doing derefence null ptr.
How to reproduce:
After cut scene, jump from the bridge, head towards the parking with a track, go under the bridge. You also can try to return to top of bridge. Result will be the same.
Culprit: opcode opcode_01c2
Log: https://gist.github.com/ShFil119/05ec8ccd8448fee25c4156169c6b2f40

**Comment by ShFil119** [comment] 2017-11-15 18:13
Script is trying to remove all unneeded pedestrians not visible on screen, so easiest way is to don't remove them. Or add some script which takes care about needed objects/pedestrians.

**Comment by husho** [comment] 2018-03-03 03:02
This is intended behavior, no need to add scripts or anything (don't really understand what you mean by that), I added nullptr checks just like in original game, so it should be fine now.

**Comment by husho** [comment] 2018-05-09 19:51
IIRC, fixed by #437.

**Comment by dracc** [comment] 2018-05-15 18:32
Can confirm, this issue is fixed with #437.

**Closed** 2018-05-18 01:11 UTC
Labels: bug, script
