### ISSUE TITLE
The graphic glitch

### ISSUE THREAD

**Issue by gbudny** [rwengine/openrw#123] opened 2016-06-03 18:17 UTC
Hi

I noticed the graphic glitch in this area of the game:

http://picpaste.com/Untitled3-QxRKclyy.png

**Comment by danhedron** [comment] 2016-06-03 19:19
This looks like a duplicate of #75

**Comment by JayFoxRox** [comment] 2016-06-10 13:24
Closed due to bad issue name (not descriptive enough) and very high likely-hood of being a duplicate of #75 . Thanks for the report though!

**Closed by JayFoxRox** 2016-06-10 13:24 UTC
