### ISSUE TITLE
Weird Scanlines on AMD laptop APU

### ISSUE THREAD

**Issue by hcorion** [rwengine/openrw#160] opened 2016-06-26 02:12 UTC
Hi all, 
I'm getting these weird scaline type effects on rwgame. Here is two screenshots:
The title screen:
![screenshot_20160625_184040](https://cloud.githubusercontent.com/assets/9814000/16360146/f9ba5140-3b05-11e6-9a5e-57e733f49154.png)
And in game:
![screenshot_20160625_184227](https://cloud.githubusercontent.com/assets/9814000/16360147/fd38b76c-3b05-11e6-8f59-5832d5adb2a7.png)
I haven't tested on this machine previously, so I don't know if it was caused by the recent move to sdl2. I will most definitly test this when the newest mesa is released also. The log looks fine:
```
I [Game] Game directory: /opt/games/Grand Theft Auto 3/
Max UBO Size: 65536
UBO Alignment: 256
Max batch size: 512
I [Renderer] OpenGL Renderer Version: 3.3 (Core Profile) Mesa 11.2.2 (GLSL 3.30) Vendor: X.Org
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
I [Data] Loaded 42 zones from /opt/games/Grand Theft Auto 3//data/gta3.zon
I [Game] Started
AL lib: (EE) alc_cleanup: 1 device not closed
```

Here are the laptop's specs:
OS: Arch Linux 64-bit
CPU: Dual Core AMD Athlon II P340
GPU: Mobility Radeon HD 4225/4250 (integrated)
Software: 
KDE Plasma 5.6.5
Linux 4.6.2
Mesa 11.2.2
X11 version 7.7
Gallium 0.4 on AMD RS880 (DRM 2.43.0, LLVM 3.8.0)
GLX Version: 1.4
Max OpenGL core profile version: 3.3
Max OpenGL compat profile version: 3.0

**Comment by hcorion** [comment] 2016-07-15 17:25
Issue still persists on mesa 12.0.1
Linux 4.6.4
KDE 5.7.1

**Comment by JayFoxRox** [comment] 2016-07-28 10:12
Can you apitrace and bisect this issue? I'm assuming this is related to water rendering, but I'm not sure.

**Comment by hcorion** [comment] 2016-07-28 17:59
Alright, so I added the return; after the line you mentioned and re-compiled it, the lines still showed up. So I removed the return; and re-compiled. and tried to do a apitrace (I'm unsure on how to do it, as I've never done it before) I uploaded the trace to google drive here: https://drive.google.com/file/d/0B2E5LNhHDNXZNXpzU3QtOVJpUUU/view?usp=sharing If this is not what you wanted, tell me and I'll get back to you.

**Comment by danhedron** [comment] 2016-08-09 20:31
This is caused by the addition of dithering, it can be fixed with the following patch:
```
diff --git a/rwengine/src/render/GameShaders.cpp b/rwengine/src/render/GameShaders.cpp
index 51d67cc..47e7d83 100644
--- a/rwengine/src/render/GameShaders.cpp
+++ b/rwengine/src/render/GameShaders.cpp
@@ -231,7 +231,6 @@ void main()
 	diffuse.rgb += ambient.rgb*ambientfac;
 	diffuse *= colour;
 	diffuse *= texture(tex, TexCoords);
-	if(visibility <= filterMatrix[int(gl_FragCoord.x)%4][int(gl_FragCoord.y)%4]) discard;
 	if(diffuse.a <= alphaThreshold) discard;
 	float fog = 1.0 - clamp( (fogEnd-WorldSpace.w)/(fogEnd-fogStart), 0.0, 1.0 );
 	fragOut = vec4(mix(diffuse.rgb, fogColor.rgb, fog), diffuse.a);
```

**Comment by danhedron** [comment] 2016-08-13 19:26
The fix for this was merged.

**Closed by danhedron** 2016-08-13 19:26 UTC
Labels: bug, graphics
